### PR TITLE
UI improvements for Signup and Login Page

### PR DESCRIPTION
**Pull request by czhou578**
Adding background pages for signup and Login pages.

### CODE REVIEW

**Comment by czhou578** [comment]
This PR isn't complete yet, but I wanted to get your thoughts on how the background images look for the Account selection and login pages, which I've completed.

**Comment by MakotoE** [comment]
It looks good. Let's store the images in the public directory to avoid hotlinking.

**Comment by czhou578** [comment]
image
In the AccountSelection file, these two routes will both direct to the user account signup. I want the bottom route to go to the vendor signup. How do I do that?

image

Changing this doesn't work.

**Comment by MakotoE** [comment]
The user creation flow starts with both the customer and the vendor going to the account creation page. Then, only the vendor goes to the create vendor page after that.

**Comment by czhou578** [comment]
When I click the vendor account in the account selection, i just sign up like normal and there is no redirection to the `VendorAppForm` page.

**Comment by MakotoE** [comment]
It works for me. Check [this line](https://github.com/bcfoodapp/streetfoodlove/blob/40f73fdea5d97238e92970b29f4cd85e7f2e486e/app/src/components/UI/Pages/Signup.tsx#L34) to make sure the correct condition is followed.

**Comment by MakotoE** [comment]
Is it at all possible to find bigger images? The 2 images that are of width 1024 looks pixelated. If not, we can keep the current images.

**Comment by czhou578** [comment]
I personally cannot find better pictures, since most of them have people I don't want a lot of people's head's being hidden behind the input forms.

**Review by MakotoE — APPROVED** [review]

**Pull request merged**
