### PR TITLE
Show location update date on vendor page

### PR DESCRIPTION
**Pull request by MakotoE**
Closes https://github.com/bcfoodapp/streetfoodlove/issues/419.

The `LastLocationUpdate` value is displayed on the vendor page next to the business address. Also, the value is updated if the vendor changed the location.

### CODE REVIEW

**Comment by czhou578** [comment]
image
Maybe change how this is worded? Maybe just state the year that it was changed.

**Comment by MakotoE** [comment]
I think you have the default date value of 0 in the database which is why it says 2021 years in the past.

**Comment by czhou578** [comment]
What do you mean by "record"?

**Comment by MakotoE** [comment]
I'm suspecting that you have a Vendor record where the `LastLocationUpdate` column is `0000-00-00 00:00:00`. You should run reset_database.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
