### PR TITLE
Add photo gallery to reviews

### PR DESCRIPTION
**Pull request by MakotoE**
Closes https://github.com/bcfoodapp/streetfoodlove/issues/230.

This adds a photo gallery to reviews to show its attached photos.

### CODE REVIEW

**Comment by czhou578** [comment]
image
The added picture name doesn't really stand out. I think the color should be changed to increase contrast. 

image
Also, I think the rendered images here can be a little bigger. What do you think about possibly having all the displayed images be the exact same height & width in the UI?

**Comment by MakotoE** [comment]
So I found that you can crop images easily with CSS. https://www.digitalocean.com/community/tutorials/css-cropping-images-object-fit I'm kind of hesitant on this decision as I worry if pictures would look good when cropped.

**Comment by czhou578** [comment]
Ok, I think cropping this way would be hard considering all the different possible contents in an image. Do you think if we sort the images by width (ascending), that would be better for the user experience? Having a wide image next to a narrow one doesn't really seem right to me.

**Comment by MakotoE** [comment]
Sorting by size is not a good idea because people can abuse the system to show certain pictures first.

**Comment by czhou578** [comment]
Ok, yes I agree. But regardless, can you find a way to make the currently displayed pictures bigger then they currently are in the UI? Not too big to make the click-to-zoom feature useless.....

**Comment by MakotoE** [comment]
This is with a height of 250px. Does this look ok?

Screenshot from 2022-02-24 11-17-38

**Comment by czhou578** [comment]
Ok, much better.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
