### PR TITLE
Recommendations Not Showing Up (BUG)

### PR DESCRIPTION
**Pull request by czhou578**
I changed the random number generator and cannot seem to get an empty recommended result now. Can you?

### CODE REVIEW

**Comment by MakotoE** [comment]
This will not fix the empty recommendations because `relevantWord` can still be a query that does not match any vendor.

**Comment by czhou578** [comment]
Relevant word would be able to match since `relevantWord` itself is generated from a list of vendors that were searched in the past. Worst case, since I'm searching through the entire list of vendors on the app for any matches, the `relevantWord` query would give back that vendor that I got the `relevantWord` from.

**Comment by MakotoE** [comment]
The relevant word column is not dependent on a list of vendors as you say. Looking [here](https://github.com/bcfoodapp/streetfoodlove/blob/62a7a2a100274d48384976449ad6e9797f08cb91/app/src/components/UI/Atoms/SearchBox/SearchBox.tsx#L68), it is dependent on the search string. So if I typed in gibberish into the search box that matches zero vendors, that string could be used as the relevant word which matches zero vendors.

**Comment by czhou578** [comment]
Ok. I understand. There is also the case where a user types in gibberish as their very first search, and that gets returned as the only past search so far. If the user hasn't searched for a proper vendor name the second time, then there wouldn't be anything to display. So should I just render a message in that space saying "No recommendations"? Maybe it can be more descriptive.

**Comment by MakotoE** [comment]
That is a good idea. Ideally, we should hide the button to show recommendations but I don't think that is possible.

**Comment by czhou578** [comment]
Yea, I'm not sure how to hide the toggle, I added an error message instead.

**Comment by MakotoE** [comment]
This doesn't address the original issue where the search result can be empty because the search string does not match any vendor.

**Comment by czhou578** [comment]
My issue is that even if I find a way to avoid the search result being empty (by generating new indexes until there is a non-empty search result), that still doesn't solve the edge case where the very first search is gibberish, as I describe above (that would just result in an infinite loop due to that gibberish being the only past search). So I think that particular message, although not perfect, is the "least worst".

**Review by MakotoE — APPROVED** [review]

**Pull request merged**
