### PR TITLE
Chart modification

### PR DESCRIPTION
**Pull request by czhou578**
I made some changes to the charts. 

Although for Chart 3, the first number that appears in the popup is representing the Month (from the code), but it looks a little bit confusing when in the chart (there is no context provided). Is this necessary?
image

### CODE REVIEW

**Comment by MakotoE** [comment]
The title is for chart 3 includes "in the last month" so if we filtered by the last month, I don't think the month label is necessary.

**Comment by czhou578** [comment]
Yeah, I agree. So that filter would just be on the frontend without changing the backend in any way right?

**Comment by MakotoE** [comment]
I think that is the best way given that we might want to be able to change the month.

**Comment by czhou578** [comment]
Do you want users to be able to choose multiple months?

**Comment by MakotoE** [comment]
I think we should just do the previous month to make it easier.

**Comment by czhou578** [comment]
Ok, yes that would be much easier.

**Comment by czhou578** [comment]
I'm going to start a new PR for that filter. I messaged Silvia about the query with "distinct" in it. Can we approve this PR?

**Review by MakotoE — APPROVED** [review]

**Pull request merged**
