### PR TITLE
Add links to search results

### PR DESCRIPTION
**Pull request by MakotoE**
The vendor names in the search result are linked to their vendor page.

### CODE REVIEW

**Comment by czhou578** [comment]
I'm typing "vendor0" into the searchbox while on the landing page because I know there is a page for that already, but there is no redirection. Which vendor pages are available to be redirected to?

**Comment by MakotoE** [comment]
The query isn't great right now and is supposed to be addressed with https://github.com/bcfoodapp/streetfoodlove/pull/307. I got some results when I typed in "v".

**Comment by czhou578** [comment]
Oh wow, yes, I do see that. Nice! 
image
Although, if a vendor doesn't have any photos, is it better to show the gallery like this, or not have the gallery rendered at all (with a message saying "no photos")?

**Comment by MakotoE** [comment]
I think hiding is better. https://github.com/bcfoodapp/streetfoodlove/issues/309

**Comment by czhou578** [comment]
Ok.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
