### PR TITLE
Reorganized Vendor Info Boxes

### PR DESCRIPTION
**Pull request by czhou578**
Close: https://github.com/bcfoodapp/streetfoodlove/issues/334

### CODE REVIEW

**Review by MakotoE — CHANGES_REQUESTED** [review]
Screenshot from 2022-05-19 09-46-49

The map looks too small now. I think the address and last updated date should be condensed to make room for the map.
The name is no longer necessary in the About Us box.

**Comment by czhou578** [comment]
I think it would be quite hard to fit the map inside that box without it overflowing, as shown in your screenshot. If I have to make one box bigger, then I will have to do the same for all the other boxes to preserve uniformity.

**Comment by MakotoE** [comment]
How about moving just the address to Contact? Keep the Last updated inside Map.

**Comment by czhou578** [comment]
Ok

**Review by MakotoE — CHANGES_REQUESTED** [review]
The name is still visible in the About Us box. Please remove the vendor name as it is already in the title.

**Review by MakotoE — APPROVED** [review]

**Pull request merged**
