### PR TITLE
Adding SQL file

### PR DESCRIPTION
**Pull request by silviacasaburi**
Please review my SQL

### CODE REVIEW

**Review by MakotoE — APPROVED** [review]

**Comment by MakotoE** [comment]
Wait a minute, your PR target branch is wrong. Look at the top.
Screenshot 2021-11-16 222315

**Comment by MakotoE** [comment]
You didn't need to fork this repo.

**Comment by silviacasaburi** [comment]
do I add the code to the main branch?
________________________________

**Comment by MakotoE** [comment]
No; Let me just give you the direct link to create a PR. https://github.com/bcfoodapp/streetfoodlove/compare/silvia?expand=1 It should say "base: main <- compare: silvia" at the top.

**Pull request merged**
