### PR TITLE
Add discount indicator

### PR DESCRIPTION
**Pull request by MakotoE**
Closes https://github.com/bcfoodapp/streetfoodlove/issues/392.

This adds an indication that a vendor is rewarding discounts. When you receive a discount after submitting a review, this is indicated below the button.

### CODE REVIEW

**Comment by czhou578** [comment]
image
I'm getting this error when trying to enable discounts in the edit vendor page. I already reset the database.

**Comment by MakotoE** [comment]
That definitely should not happen. Are you sure you made no changes to database.go?

**Comment by czhou578** [comment]
Besides pulling the changes from remote, I'm pretty sure.

**Comment by MakotoE** [comment]
This PR doesn't make any changes to the SQL commands, so it must be something on your side.

**Comment by czhou578** [comment]
Oh wait, I see something....

**Comment by czhou578** [comment]
Ok. Yeah, it was something on my end. 
image
Can you add a little bit of margin on the bottom, and maybe make this particular line bold?

**Comment by MakotoE** [comment]
I added space to the bottom. I don't think there is a semantic reason to bold the text because I don't think it is as important.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
