### PR TITLE
Set header menu icon to user photo

### PR DESCRIPTION
**Pull request by MakotoE**
The user photo ID is saved to localStorage so that the profile picture can be displayed in the header bar. The header bar icon is updated to use the user photo.

### CODE REVIEW

**Comment by czhou578** [comment]
image
This is minor, but can you find a way to vertically align the downward arrow with the middle of the profile pic?

**Comment by MakotoE** [comment]
Looking at examples, it looks like the dropdown icon is supposed to go on the right so I was able to fix it to do that. I noticed that one of the menu dividers doesn't reach the bottom of the header bar so I fixed this by changing the search bar font size to normal.

Screenshot from 2022-03-04 10-33-24

**Comment by czhou578** [comment]
Can you commit those changes?

**Comment by MakotoE** [comment]
Thanks for reminding me; I forgot to do that.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
