### PR TITLE
Make review rating input functional

### PR DESCRIPTION
**Pull request by MakotoE**
This makes it so that selected rating in the review form is sent with the review request.

### CODE REVIEW

**Comment by MakotoE** [comment]
@czhou578 Can you check why my selected rating is not showing in the stars? For example:

1. Click on 3rd star
2. Only 1 star is yellow and the rest is grey
3. But when I submit the review, `starRating` in `ReviewForm` is 3

**Comment by czhou578** [comment]
image
I think you have to click in the center of the star.

**Comment by MakotoE** [comment]
I fixed the stars issue with the latest commit by using equality operators instead of greater than. I don't know how this is even working but it fixed the issue.

**Comment by czhou578** [comment]
Are you talking about the greater then signs in the CSS?

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
