### PR TITLE
Add profile picture input to AccountSettingsFormGroup

### PR DESCRIPTION
**Pull request by MakotoE**
This adds a drag-and-drop component to `AccountSettingsFormGroup` for uploading a profile picture.

### CODE REVIEW

**Comment by czhou578** [comment]
image

I'm not sure what the profile icon is doing below the upload section. Is it meant to signify that this area is to upload a profile pic? If it is, then I think it makes more sense to have it on the right of the "profile picture" header

**Comment by MakotoE** [comment]
That is the current profile picture.

**Comment by czhou578** [comment]
Ok. I think it would be better if there was some sort of header like "current profile pic" that would make that clear. What do you think?

**Comment by MakotoE** [comment]
I added a label for the current profile picture. I think that it would be more ideal if the header bar displayed the current profile picture. The profile picture below the image input could be considered temporary which will be removed once the header bar shows the current picture.

**Comment by czhou578** [comment]
Ok. We'll create a separate issue for that.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
