### PR TITLE
Add Discount page

### PR DESCRIPTION
**Pull request by MakotoE**
The Discount page is accessed from the discount list. It displays the QR code to show to the vendor and claim the discount.

### CODE REVIEW

**Comment by czhou578** [comment]
image
 I reset the database and left a review for `Great Clips`, but I found that the vendor name `Great Clips` didn't appear in the discounts part of Account Settings. This is what I got when I navigate to the discount page.

**Comment by MakotoE** [comment]
Probably 2 issues were happening: you forgot to enable discount exchange, and caching problems that I fixed using tags.

**Comment by MakotoE** [comment]
Probably 2 issues were happening: you forgot to enable discount exchange, and caching problems that I fixed using tags.

**Comment by czhou578** [comment]
image
Is this link supposed to be broken? It says "page not found".

**Comment by MakotoE** [comment]
That page does not exist yet as it is a work in progress.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
