### PR TITLE
EditVendorPage - Set business address when coordinate was inputted

### PR DESCRIPTION
**Pull request by MakotoE**
Closes https://github.com/bcfoodapp/streetfoodlove/issues/405.

When the vendor sets the location using their coordinates, the business address for that coordinate is set.

### CODE REVIEW

**Comment by czhou578** [comment]
image
I'm wondering if we can change the button to say like "Get my coordinates and address". Or we can make the current address line a little bit more visible.

**Comment by MakotoE** [comment]
Maybe "Get my coordinates and address" doesn't explain that it uses the GPS. How about "Use GPS coordinates and address"?

**Comment by czhou578** [comment]
Ok

**Comment by MakotoE** [comment]
I have changed the button text.

**Comment by czhou578** [comment]
Looks good.

**Review by czhou578 — APPROVED** [review]

**Pull request merged**
