### PR TITLE
Created React App

### PR DESCRIPTION
**Pull request by czhou578**
created react-app

### CODE REVIEW

**Comment by MakotoE** [comment]
I don't like create-react-app because I think it makes things more complicated rather than simplify it. If you want to use CRA, that's fine. Just move all the files from `app/streetfoodlove` to `app` to avoid the extra directory.

**Comment by MakotoE** [comment]
I changed my mind. CRA doesn't generate too many files so that is good. I'm willing to go with CRA. We will have to remove the CRA framework at some point though.

**Comment by MakotoE** [comment]
The files are still in `streetfoodlove/app/streetfoodlove`. The `streetfoodlove/app/streetfoodlove` directory is unnecessary and all the files in there can be moved to `streetfoodlove/app`. You can replace the current  streetfoodlove/app/package.json  with the one you made.

**Comment by MakotoE** [comment]
How do you run this? When I do `yarn start`, I get this error:
```
Could not find a required file.
  Name: index.html
  Searched in: /home/makoto/Documents/streetfoodlove/app/public
```

**Comment by czhou578** [comment]
Try "npm start"

**Comment by MakotoE** [comment]
npm outputs the same error.

**Comment by MakotoE** [comment]
I see that you deleted `app/streetfoodlove/public/index.html` on the latest commit.

**Comment by czhou578** [comment]
Wait, I don't even remember an index.html file being in the directory when I created the react-app.

**Comment by MakotoE** [comment]
It was [here](https://github.com/bcfoodapp/streetfoodlove/blob/425484ea823d2286b7c6a49a3069df8b55715176/app/streetfoodlove/public/index.html) in your previous commit, then you removed it [here](https://github.com/bcfoodapp/streetfoodlove/pull/3/commits/652b8bffde7863441898b34cf5ea3b72fdc4448a#diff-6d1e67ea807731720e308975a008fe00f3e9eecde391461c8b02ca3eec9414f7)

**Comment by czhou578** [comment]
Sorry for the error. It should be fixed now. Run the app and you will see the error I was originally describing.

**Comment by MakotoE** [comment]
That error for react-leaflet appears because you are still importing it with `import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';` in Map.jsx. Comment out that line. I still got an error about `reportWebVitals();` and I don't know what that is for so I also removed that.

**Comment by czhou578** [comment]
Ok. I did that. Can you do the webpack modification?

**Comment by MakotoE** [comment]
It doesn't look like you committed it.

**Comment by czhou578** [comment]
Pushed.

**Review by MakotoE — APPROVED** [review]

**Pull request merged**
