### PR TITLE
Business Guide PDF Download

### PR DESCRIPTION
**Pull request by czhou578**
Users will be able to download the Business Guides as an individual PDF. 

Note: After pressing the button to download, you have to wait 2-3 seconds for the file to be generated.

### CODE REVIEW

**Comment by czhou578** [comment]
image
image
@MakotoE I managed to generate the pdf, but some parts of it is cut off like this. Also, I cannot increase the left margins or else the text will be cut off. What do you think of this so far?

**Comment by MakotoE** [comment]
It would be a lot easier to read if the PDF contained text and not images of text. Is there no way to export a PDF containing the text of the article?

**Comment by czhou578** [comment]
I'll do more research into it.

**Comment by czhou578** [comment]
@MakotoE I found a way to do it with the React-pdf library. But I'm going to have to completely change the formatting of the existing business guides in the project to use the tags that are specific to the library. 
image
Just for reference, this is the amount of code needed to generate an unordered list with 3 items. 
There are a lot of unordered lists in the articles Selina wrote, not to mention there are a lot of short paragraphs, which I don't know whether Selina would agree to combining them all.

**Comment by MakotoE** [comment]
I don't like this idea at all. We should use tags we are used to and not force ourselves (and potential authors) to learn new ones just to enable the ability to create PDFs.

**Comment by czhou578** [comment]
From my research, we can either use jsPdf and html2canvas (my very first approach), or use a dedicated library like react-pdf with its own set of tags. I have used the jsPdf and html2canvas approach before and the pdf that's generated seems to be pretty clear in terms of resolution on my end. What do you think? I do agree that the react-pdf approach isn't the best at all, but we don't have too many options.

**Comment by MakotoE** [comment]
Let's stick with the method you used in this PR. Instead of using `document.getElementById()`, use [`useRef()`](https://reactjs.org/docs/hooks-reference.html#useref).

**Comment by czhou578** [comment]
@MakotoE I'm using useRef, but the `useRef.current` property is null, which is breaking the download. I know that the ref is not going to set on the first render, but I'm not sure how to solve this. Can you take a look? Look at `Article1.tsx` specifically.

**Comment by MakotoE** [comment]
You can only reference a DOM element such as a `<div>`, but Container is a functional component. It tells you in the console if you attempted to do this.

**Comment by czhou578** [comment]
I got the downloading to work! Can you please check `Article1.tsx`? If this is good with you, I'm going to do the same for all the other Article components.

**Comment by czhou578** [comment]
I just replaced the Container with the original html div element, since I cannot figure out any other way.

**Comment by MakotoE** [comment]
Article 1 is working fine.

**Comment by czhou578** [comment]
image
Also, I want to make the download button show that it is loading while the download is happening (to prevent multiple clicks). I did a setTimeOut for 3 seconds, are you ok with this?

**Comment by MakotoE** [comment]
That could work but you already know when `downloading` should be false which is after `doc.save()` so you should set it to false after that instead of using timeout.

**Comment by czhou578** [comment]
Yeah, I tried that already actually. But if I set the downloading state to false right after the doc.save, the button state will never set to true (which would enable the loading animation).

**Comment by MakotoE** [comment]
I see that it returns a `Promise`, so try calling `setDownloading()` after it resolves. https://rawgit.com/MrRio/jsPDF/master/docs/jsPDF.html#save

**Comment by czhou578** [comment]
That fixes it perfectly! Thanks!

**Review by MakotoE — APPROVED** [review]

**Pull request merged**
